Repository AY2425S2-CS2113-F11-3/tp, pull requests merged in 2025-04, with the labels that each got.

#151 Fixed bug in convert ingredient method
  src/main/java/pantrypal/inventory/IngredientInventory.java
Labels: priority.High, type.Enhancement

#152 Updated Portfolio docs name to match github username
  docs/AboutUs.md
  docs/team/kemilii.md
  docs/team/srfl0.md
  docs/team/yok2086.md
Labels: type.Task

#155 Updated Portfolio Page
  docs/team/johndoe.md
  docs/team/yok2086.md
Labels: type.Task

#248 Resolved Issues: #243, #217, #221, #212 #220
  .gitignore
  docs/DeveloperGuide.md
  docs/Parser_Sequence_Diagram.png
  docs/team/h-zhanhao.md
  src/main/java/pantrypal/general/commands/general/Help.java
  src/main/java/pantrypal/general/commands/inventory/AddIngredient.java
  src/main/java/pantrypal/general/commands/inventory/ConvertIngredient.java
  src/main/java/pantrypal/general/commands/inventory/DecreaseQuantity.java
  src/main/java/pantrypal/general/commands/inventory/DeleteIngredient.java
  src/main/java/pantrypal/general/commands/mealplan/AddPlan.java
  src/main/java/pantrypal/general/commands/mealplan/AddPlanToDay.java
  src/main/java/pantrypal/general/commands/mealplan/AddRecipeToPlan.java
  src/main/java/pantrypal/general/commands/mealplan/ExecutePlanForDay.java
  src/main/java/pantrypal/general/commands/mealplan/FindForPlans.java
  src/main/java/pantrypal/general/commands/mealplan/RemovePlanFromDay.java
  src/main/java/pantrypal/general/commands/mealplan/RemoveRecipeFromPlan.java
  src/main/java/pantrypal/general/commands/recipe/EditRecipeInstruction.java
  src/main/java/pantrypal/general/commands/recipe/RemoveRecipe.java
  src/main/java/pantrypal/general/commands/recipe/ViewRecipe.java
  src/main/java/pantrypal/general/commands/shoppinglist/AddShoppingItem.java
  src/main/java/pantrypal/general/control/DataCorruptionException.java
  src/main/java/pantrypal/general/control/Parser.java
  src/main/java/pantrypal/general/control/Storage.java
  src/main/java/pantrypal/inventory/IngredientInventory.java
  src/main/java/pantrypal/mealplan/MealPlanManager.java
  src/main/java/pantrypal/shoppinglist/ShoppingListItem.java
  src/test/java/pantrypal/general/control/ParserTest.java
Labels: type.Bug
